### ISSUE TITLE
Error when jsweet-maven-plugin has target version ES6

### ISSUE THREAD

**Issue by peperomeu** [j4ts/j4ts#9]
I've cloned the jsweet quickstart project and I put the plugin target version to ES6, just to see the js code that it generates. When I execute `mvn generate-sources`, I get the following error:

```
2016-10-27 10:13:31.031 INFO  JSweetTranspiler:1076 - launching tsc...
2016-10-27 10:13:31.031 DEBUG ProcessUtil:178 - run command: C:\Users\Lucas\.jsweet-node_modules\tsc.cmd --target ES6 --rootDir C:\Users\Lucas\Proyectos\Pruebas\jsweet-quickstart\target\ts --outDir C:\Users\Lucas\Proyectos\Pruebas\jsweet-quickstart\target\js .tsc-rootfile.ts quickstart\QuickStart.ts ..\..\.jsweet\candies\typings\src\typings\j4ts\0.2.0-SNAPSHOT\.tsc-rootfile.d.ts ..\..\.jsweet\candies\typings\src\typings\j4ts\0.2.0-SNAPSHOT\bundle.d.ts ..\..\.jsweet\candies\typings\src\typings\jquery\jquery.d.ts ..\..\.jsweet\candies\typings\src\typings\sprintf-js\sprintf-js.d.ts
2016-10-27 10:13:33.033 INFO  JSweetTranspiler:1081 - ../../.jsweet/candies/typings/src/typings/j4ts/0.2.0-SNAPSHOT/bundle.d.ts(8566,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Map' must be of type 'MapConstructor', but here has type 'Object'.
ERROR: subsequent variable declarations must have the same type.  Variable 'Map' must be of type 'MapConstructor', but here has type 'Object' at ..\..\.jsweet\candies\typings\src\typings\j4ts\0.2.0-SNAPSHOT\bundle.d.ts(8566)
2016-10-27 10:13:33.033 INFO  JSweetTranspiler:616 - transpilation process finished in 2955 ms
[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 1 error(s) and 3 warning(s)
        at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:304)
        at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

The versions I've installed are:
- Windows 7 SP 1
- java version "1.8.0_102"
- node version v6.8.1
- npm version 3.9.6

**Comment by renaudpawlak** [comment]
Thank you for reporting. It works for ES3, ES5, but not for ES6, indeed.

I will investigate ASAP.

**Comment by lgrignon** [comment]
I close because ES6 is supported in last version
